### ISSUE TITLE
How to install this extension?

### ISSUE THREAD

**Issue by aWeinzierl** [luyiming/UniFormatter#1]
I am running VSCode and would like to use the extension - what steps do I need to perform to use this extension?

**Comment by luyiming** [comment]
This project is no longer maintained. I have read a blog before which tells the design choices of VSCode. The maintainers of VSCode prefer one language pack extension covering all the functionalities for that language, rather than a universal extension covering one same functionality for all languages. 

So if you want to use the formatter, you just need to install the corresponding extension for your language. No need for the universal formatter.

**Comment by aWeinzierl** [comment]
Unfortunately, this extension seems to be the only one which supported bibtex. Otherwise, I would have installed the corresponding extension already.

Thank you for your reply.
